on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'after'
        run: ls


      -name: "login to docker hub"
       run: docker login --username ${{ secrets.DOCKER-USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}